package com.opensourceforlife.portlet.samplerecyclebin.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.opensourceforlife.portlet.samplerecyclebin.model.Event;
import com.opensourceforlife.portlet.samplerecyclebin.service.EventLocalServiceUtil;

/**
 * The extended model base implementation for the Event service. Represents a row in the &quot;SRB_Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventImpl}.
 * </p>
 *
 * @author Opensourceforlife
 * @see EventImpl
 * @see com.opensourceforlife.portlet.samplerecyclebin.model.Event
 * @generated
 */
public abstract class EventBaseImpl extends EventModelImpl implements Event {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a event model instance should use the {@link Event} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EventLocalServiceUtil.addEvent(this);
        } else {
            EventLocalServiceUtil.updateEvent(this);
        }
    }
}
